language: c
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
  - wget https://raw.githubusercontent.com/simonjbeaumont/ocaml-travis-coveralls/master/travis-coveralls.sh
script: bash -ex .travis-opam.sh
sudo: required
dist: trusty
env:
  global:
    - PACKAGE="qcow-tool" OCAML_VERSION=4.03
    - EXTRA_REMOTES="https://github.com/djs55/opam-repository.git#io-page"
    - PINS="qcow:. mirage-block-ramdisk:https://github.com/mirage/mirage-block-ramdisk.git"
    - COV_CONF="export TESTS=--enable-tests"
    - PRE_INSTALL_HOOK="sudo apt-get install qemu-utils -y"
