version: 2
jobs:
  build:
    docker:
      - image: ocaml/opam2:alpine
    steps:
      - checkout
      - run: env
      - run: opam pin add qcow .
      - run: opam config exec -- make
      - store_artifacts:
          path: _build/default/cli/main.exe
          destination: qcow-toolt
