version: 2
jobs:
  build:
    macos:
      xcode: "11.3.1"
    environment:
      # OPAM seems to be quite unhappy without $TERM and Circle doesn't seem to set one.
      TERM: vt100
      MACOSX_DEPLOYMENT_TARGET: "10.11"
      OPAM_REPO: repo/darwin
      OPAM_COMP: 4.10.0
      OPAMVERBOSE: 1
      OPAMYES: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - run: env
      - run: brew install opam
      - run: opam init -v -n --comp="${OPAM_COMP}" --switch="${OPAM_COMP}" local "${OPAM_REPO}"
      - run: opam pin add qcow .
      - run: opam config exec -- make
      - store_artifacts:
          path: _build/default/cli/main.exe
          destination: qcow-tool
